"""update APIkey model: label is unique

Revision ID: de3e1ea36f24
Revises: b054596ff2c6
Create Date: 2025-12-03 14:52:32.693493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3e1ea36f24'
down_revision: Union[str, Sequence[str], None] = 'b054596ff2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apikeys', ['label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apikeys', type_='unique')
    # ### end Alembic commands ###
